name: Sync E2E

on:
  repository_dispatch:
    types: [api-push, ui-push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.E2E_PAT }}

      - name: Sync API
        uses: actions/checkout@v4
        with:
          repository: abdelaziz-ebourki/estore-api
          path: estore-api
          token: ${{ secrets.E2E_PAT }}

      - name: Sync UI
        uses: actions/checkout@v4
        with:
          repository: abdelaziz-ebourki/estore-ui
          path: estore-ui
          token: ${{ secrets.E2E_PAT }}

      - name: Commit & Push
        run: |
          git config user.name "e2e-bot"
          git config user.email "e2e-bot@users.noreply.github.com"
          git add estore-api estore-ui
          if ! git diff --cached --quiet; then
            git commit -m "sync: update estore-api & estore-ui"
            git push
          fi
